spring:
  datasource:
    url: jdbc:${POSTGRES_DATABASE_URL:postgresql://localhost:5432/blogdb}
    driver-class-name: org.postgresql.Driver
    #local
    #    username: postgres
    #    password: mysimplepass
    #production
    username: gmfnoixmhspikv
    password: 82079c6fddde324bd34a1e550912f56f1f5a66150dfab28f954bc41a1ac6f3c6
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    #local
#        username: postgres
#        password: mysimplepass
    #production
    username: gmfnoixmhspikv
    password: 82079c6fddde324bd34a1e550912f56f1f5a66150dfab28f954bc41a1ac6f3c6
    url: jdbc:${POSTGRES_DATABASE_URL:postgresql://localhost:5432/blogdb}
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mail:
    address: devpub@rambler.ru
    host: email-smtp.us-east-2.amazonaws.com
    port: 587
    username: AKIAUMFYGWQRXW27DKFL
    password: BPXwGQ7br199/vduHr5+ovyyXfkoyQYXpbq/Lr54W5fq
    properties:
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 930 2748482
  email: ivan-fomkin@yandex.ru
  copyright: Иван Фомкин
  copyrightFrom: 2019

content:
  post:
    minimum-text-length: 50
    minimum-title-length: 3
  comment:
    minimum-comment-length: 2
  password:
    minimum-password-length: 6
  user:
    minimum-name-length: 4
    maximum-name-length: 30


storage:
  location: upload
  max-file-size: 10MB
  image-width: 36
  image-height: 36
  default-avatar: /upload/default_avatar.jpg

captcha:
  length: 5
  #in minutes
  drop-time: 60

server:
  port: ${PORT:8080}
