spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: mysimplepass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    password: mysimplepass
    user: postgres
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mail:
    host: smtp.yandex.ru
    port: 465
    username: d3vpub
    password: testPassword
    properties:
      "mail.smtp.ssl.enable": true

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 930 2748482
  email: ivan-fomkin@yandex.ru
  copyright: Иван Фомкин
  copyrightFrom: 2019

storage:
  location: upload
  max-file-size: 10MB
  image-width: 36
  image-height: 36

captcha:
  length: 5
  #in minutes
  drop-time: 60
