spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: mysimplepass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    password: mysimplepass
    user: postgres
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 930 2748482
  email: ivan-fomkin@yandex.ru
  copyright: Иван Фомкин
  copyrightFrom: 2019

storage:
  location: upload
  max-file-size: 10MB

captcha:
  length: 5