create table captcha_codes
(
    id          int4 generated by default as identity,
    code        varchar(80) not null,
    secret_code varchar(80) not null,
    time        timestamp   not null,
    primary key (id)
);

create table global_settings
(
    id    int4 generated by default as identity,
    code  varchar(255),
    name  varchar(255),
    value varchar(255),
    primary key (id)
);

create table post_comments
(
    id        int4 generated by default as identity,
    text      text      not null,
    time      timestamp not null,
    parent_id int4,
    post_id   int4      not null,
    user_id   int4      not null,
    primary key (id)
);

create table post_votes
(
    id      int4 generated by default as identity,
    time    timestamp not null,
    value   int2      not null,
    post_id int4      not null,
    user_id int4      not null,
    primary key (id)
);

create table posts
(
    id                int4 generated by default as identity,
    is_active         int4         not null,
    moderation_status varchar(255) not null,
    text              text         not null,
    time              timestamp    not null,
    title             varchar(255) not null,
    view_count        int4         not null,
    moderator_id      int4,
    user_id           int4         not null,
    primary key (id)
);

create table tag2post
(
    id      int4 generated by default as identity,
    post_id int4 not null,
    tag_id  int4 not null,
    primary key (id)
);

create table tags
(
    id   int4 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table users
(
    id           int4 generated by default as identity,
    code         varchar(255),
    email        varchar(255) not null,
    is_moderator int4         not null,
    name         varchar(255) not null,
    password     varchar(255) not null,
    photo        text,
    reg_time     timestamp    not null,
    primary key (id)
);

alter table if exists post_comments
    add constraint FKc3b7s6wypcsvua2ycn4o1lv2c foreign key (parent_id) references post_comments;
alter table if exists post_comments
    add constraint FKaawaqxjs3br8dw5v90w7uu514 foreign key (post_id) references posts;
alter table if exists post_comments
    add constraint FKsnxoecngu89u3fh4wdrgf0f2g foreign key (user_id) references users;
alter table if exists post_votes
    add constraint FK9jh5u17tmu1g7xnlxa77ilo3u foreign key (post_id) references posts;
alter table if exists post_votes
    add constraint FK9q09ho9p8fmo6rcysnci8rocc foreign key (user_id) references users;
alter table if exists posts
    add constraint FK6m7nr3iwh1auer2hk7rd05riw foreign key (moderator_id) references users;
alter table if exists posts
    add constraint FK5lidm6cqbc7u4xhqpxm898qme foreign key (user_id) references users;
alter table if exists tag2post
    add constraint FKpjoedhh4h917xf25el3odq20i foreign key (post_id) references posts;
alter table if exists tag2post
    add constraint FKjou6suf2w810t2u3l96uasw3r foreign key (tag_id) references tags;
